### ISSUE TITLE
No Linters dependency installed

### ISSUE THREAD

**Issue by carlosmuerto** [robinbenitezmora/ToDoList-Webpack#2]
# No Linters dependency installed
I find that you don't have your Linters properly installed

``` bash
npm install --save-dev hint@7.x
```
``` bash
npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x
```
``` bash
npm install --save-dev eslint@7.x eslint-config-airbnb-base@14.x eslint-plugin-import@2.x babel-eslint@10.x
```
https://github.com/robinbenitezmora/ToDoList-Webpack/blob/d1eb93631167b438058d1ca5758644e82664ae88/package.json#L272-L284

**Comment by robinbenitezmora** [comment]
Agree with Carlos's suggestion were installed the commands given.
